"""updated Image table

Revision ID: 474da9c44023
Revises: c36c837facd8
Create Date: 2021-08-09 13:33:17.388914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474da9c44023'
down_revision = 'c36c837facd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
